# Adopt Flutter's recommended lints
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style preferences
    prefer_single_quotes: true
    # If you want to enforce docs across public API, uncomment the next line:
    # public_member_api_docs: true
    #
    # Other handy rules you might like:
    # avoid_print: true
    # always_declare_return_types: true
    # directives_ordering: true
    # unnecessary_this: true
    # prefer_const_constructors: true
    # prefer_final_locals: true
