name: pos_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1      # <--- THIS IS THE IMPORTANT LINE
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  lottie: ^3.3.1
  go_router: ^14.0.2
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_splash.jpg
