name: pos_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  lottie: ^3.3.1
  go_router: ^16.1.0
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.2.1
  fl_chart: ^0.66.2
  flutter_vector_icons: ^2.0.0
  mobile_scanner: ^3.5.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.2
  path_provider: ^2.1.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/item/
    - assets/cat/bakery.png
    - assets/cat/beverages.png
    - assets/cat/snacks.png
    - assets/cat/drinks.png
    - assets/cat/grocery.png
    - assets/cat/household.png
    - assets/cat/dairy.png



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pos_logo.png"
  min_sdk_android: 21
